export const selectList = {
	searchGb: '',
	firstIndex: '1',
	lastIndex: '1',
	pageSize: 4,
	pageUnit: '10',
	recordCountPerPage: '10',
	sbscrbSttus: '',
	searchCondition: '',
	search_val: '',
	search_key: '',
	searchCdKey: '',
	parntsBdongCd: '',
	emgncContactNtwkSeCd: '2',
	orgSeCd: '02',
	q_area_cd_3: '',
	q_onefour: '',
	hdaySe: '',
	edcTgtSeCd: '',
	cvdpyCpsCode: '',
	cvdEduSeCode: '',
	edYmd: '',
	edSno: '',
	rdn_code: ''
};
